help: ## display this help message
	@echo "Please use \`make <target>' where <target> is one of"
	@perl -nle'print $& if m{^[a-zA-Z_-]+:.*?## .*$$}' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m  %-25s\033[0m %s\n", $$1, $$2}'

clean: ## remove generated byte code, coverage reports, and build artifacts
	find . -name '__pycache__' -exec rm -rf {} +
	find . -name '*.pyc' -exec rm -f {} +
	find . -name '*.pyo' -exec rm -f {} +
	find . -name '*~' -exec rm -f {} +
	rm -fr build/
	rm -fr dist/
	rm -fr media/
	rm -fr *.egg-info
	rm -rf db.sqlite3

clean_migrations:
	find . -path "*/migrations/*.py" -not -name "__init__.py" -delete
	find . -path "*/migrations/*.pyc"  -delete

migrate:
	python manage.py migrate

make_migrations:
	python manage.py makemigrations

requirements:
	virtualenv -q -p /usr/bin/python3.8 venv
	venv/bin/pip install -r requirements/requirements.txt

load_data:
	venv/bin/python3.8 manage.py loaddata data.json

run:
	venv/bin/python3.8 manage.py runserver

restart: clean clean_migrations make_migrations migrate

